# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      #      - id: isort
      #        name: isort
      #        entry: "poetry run isort app"
      #        language: system
      #        pass_filenames: false
      #        always_run: true
      - id: black
        name: black
        entry: "poetry run black src"
        language: system
        pass_filenames: false
        always_run: true
      - id: lint
        name: Lint
        entry: "poetry run ruff megad --fix"
        types: [python]
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy-check
        entry: "poetry run mypy --strict megad"
        language: system
        pass_filenames: false
        always_run: true
      # - id: pytest-check
      #   name: pytest-check
      #   entry: "poetry run pytest --cov src --cov-report json"
      #   language: system
      #   pass_filenames: false
      #   always_run: true
      # - id: check-coverage
      #   name: check-coverage
      #   entry: "poetry run python3 tools/cov-to-file.py --file 0.9 **/*.py"
      #   language: system
      #   pass_filenames: false
      #   always_run: true
